### ISSUE TITLE
Gmail api & implementation

### ISSUE THREAD

**Issue by BUicicchen** [BU-Spark/project-engage#16]
**Is your feature request related to a problem? Please describe.**
1. Automated email: Invite users to sign up
"Hey you have been invited to sign up as xxx, click here (insert applicant portal link) to sign up!"
2. Customized emails
write emails to potential employees

(make sure we have interactive content, workable links, etc.)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

@jfeng5529 @BUicicchen

**Comment by rishabnayak** [comment]
these need UI's
