### ISSUE TITLE
Project-engage dashboard front-end

### ISSUE THREAD

**Issue by ksapru** [BU-Spark/project-engage#17]
1. ~~Write new code using the grid system and commit it using Github Desktop without direct commits~~
2. ~~Integrate the front and back end~~
3. ~~Wait for the design~~

**Comment by ksapru** [comment]
- New code using grid system complete and tested for responsiveness
- Awaiting approval to commit to git

**Comment by ksapru** [comment]
Next week (04/05):

- Link a **new** admin page using conditional rendering 
- Remove the container from the existing page and figure out a borderless solution 
- Continuously communicate with other teams, especially for the UI

**Comment by ksapru** [comment]
- Shadow issue with the Google Login button (04/19)

**Comment by BUicicchen** [comment]
> * Shadow issue with the Google Login button (04/19)
> * Spacing & size issue with the container (04/19)
> * Router link/Admin Login Form (04/19)
